### ISSUE TITLE
Calling Array formatter is slow for large arrays

### ISSUE THREAD

**Issue by gwgundersen** [alexhsamuel/fixfmt#13]
**Example:**

```
arr = np.zeros((50,50,1000))
fmt = Array(Number(3, 2))
s = fmt(arr)
```

Is this an issue or expected?

**Comment by gwgundersen** [comment]
@alexhsamuel, what do you think?

**Comment by alexhsamuel** [comment]
I think this is from using the `s += ...` pattern to construct a 23 MB string. Each append can cause a new allocation, so the operation is N^2 in the string length. A somewhat more efficient pattern for building very long strings is to produce parts of the big string from a generator, and `"".join(...)` them at the end. Even this could take a while, though. If you plan to reimplement this in C++, there are other strategies to use.

Is this really what you want to do, though? If you are going to paginate it, it's probably better to produce a page at a time on demand, rather than producing all the output and handing it to the pager. (By the way, `pydoc.pager()` immediately shows the string, which is not what we want in a formatter's `__call__`.)

I don't think returning 23 MB of array output is a very useful feature. We should probably strategize about what kind of interactive features we'd hope to provide for working with large datasets. I'd say punt on performance for now and make it work the way you want it for small arrays, and let's address large / interactive viewing separately.

**Comment by gwgundersen** [comment]
Thanks for the feedback. That was very useful. I think need to create a page on demand. Since this is related to the implementation (issue #9), I'll close this for now.
